os:
- linux
language: php
php:
- 7.2
- 7.3
- 7.4
before_install:
- composer self-update
cache:
  directories:
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"
install:
- travis_retry composer install --no-interaction --prefer-source
script: "./run-tests.sh"
notifications:
  email: false
